### ISSUE TITLE
Avoid needing to create lifetimescope

### ISSUE THREAD

**Issue by camiller2** [chase-miller/Autofac.Extras.IdentityServer3#12]
Avoid needing to do the code around https://github.com/chase-miller/Autofac.Extras.IdentityServer3/blob/master/Autofac.Extras.IdentityServer3/Extensions/TypeRegistrationExtensions.cs#L151 and https://github.com/chase-miller/Autofac.Extras.IdentityServer3/blob/master/Autofac.Extras.IdentityServer3/Extensions/TypeRegistrationExtensions.cs#L236

**Comment by chase-miller** [comment]
Addressed in https://github.com/chase-miller/Autofac.Extras.IdentityServer3/pull/15

**Comment by chase-miller** [comment]
Addressed in https://github.com/chase-miller/Autofac.Extras.IdentityServer3/pull/15
